### ISSUE TITLE
Apply with Linkedin

### ISSUE THREAD

**Issue by lauhakari** [mikejolley/WP-Job-Manager#473]
You have a plugin for applying with linkedin. I'm guessing that doesn't work anymore after they changed their API and rules?

**Comment by mikejolley** [comment]
It does if they give you access. You need to apply: https://wpjobmanager.com/document/apply-with-linkedin/#section-1

**Comment by RichardLindhout** [comment]
Hmm, but it also tries to get something of a undefined object (my positions where in the api but not my skills.)
It crashed at skills.


I fixed in the resume-submission.js
```
   $(profile.skills.values).each(function (i, e) {
```

with first checking if object is not undefined
    if(profile.skills) {

I did that for all the rest of the things skills, memberUrlResources.

but @mikejolley is right, when linkedIn does give everything no undefined is thrown. But I think they should add these fixes.

**Comment by jom** [comment]
Hi @RichardLindhout! We're aware of that issue and are tracking it with the resume plugin. Thank you!

**Comment by etalented** [comment]
I still have an issue with this- where can I get the solution?
![screen shot 2017-07-17 at 09 49 35](https://user-images.githubusercontent.com/20968408/28260973-4a0a3e1c-6ad5-11e7-9a5b-3cc763789510.png)

**Comment by Hocine123** [comment]
I am having some weird isseu with Linkein App API integration, I create the App, I add the key to wp-job manger and added the url, but it does not work, I recorded this video here if you can help, whtaè is the redirect url...Thnak you 
https://www.useloom.com/share/1d09fa08680c4ff3b40daffd878a0f18

**Comment by richardmtl** [comment]
@Hocine123 We're aware of this issue, and as I mentioned to you via email, we'll get back to you when we know if we can fix the Applications add-on, or if we have to remove that functionality from the add-on. Thanks!

**Comment by Gnodesign** [comment]
Just in case anyone is interest, I have created an addon to allow users to apply to a job via their LinkedIn account. **WP Job Manager- Applications** is require in order for this to fully work.

https://codecanyon.net/item/linkedin-for-wp-job-manager/32425444

**Comment by carnelianfox** [comment]
> 
https://github.com/Gnodesign


> Just in case anyone is interest, I have created an addon to allow users to apply to a job via their LinkedIn account. **WP Job Manager- Applications** is require in order for this to fully work.
> 
> https://codecanyon.net/item/linkedin-for-wp-job-manager/32425444

Hi Gnodesign.

I paid for this plugin from codecanyon just a few days ago. I have been able to get  it working to the point where it requests LinkedIn permissions but beyond that the page returns a wordpress error. I opened a ticket on your support page and added in my purchase code. Your help is urgently needed on this please.

Thanks,
